<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="5" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-01-10T20:02:13 IST" name="Default suite" finished-at="2021-01-10T20:02:13 IST" duration-ms="89">
    <groups>
    </groups>
    <test started-at="2021-01-10T20:02:13 IST" name="Default test" finished-at="2021-01-10T20:02:13 IST" duration-ms="89">
      <class name="TestCalculate">
        <test-method is-config="true" signature="init()[pri:0, instance:TestCalculate@6a2b953e]" started-at="2021-01-10T20:02:13 IST" name="init" finished-at="2021-01-10T20:02:13 IST" duration-ms="8" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="emptyStringReturnsZero()[pri:0, instance:TestCalculate@6a2b953e]" started-at="2021-01-10T20:02:13 IST" name="emptyStringReturnsZero" finished-at="2021-01-10T20:02:13 IST" duration-ms="22" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emptyStringReturnsZero -->
        <test-method signature="negativeInputReturnsException()[pri:0, instance:TestCalculate@6a2b953e]" started-at="2021-01-10T20:02:13 IST" name="negativeInputReturnsException" finished-at="2021-01-10T20:02:13 IST" duration-ms="5" status="FAIL">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method TestCalculate.negativeInputReturnsException()[pri:0, instance:TestCalculate@6a2b953e] should have thrown an exception of type class java.lang.Exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method TestCalculate.negativeInputReturnsException()[pri:0, instance:TestCalculate@6a2b953e] should have thrown an exception of type class java.lang.Exception
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:747)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:635)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeInputReturnsException -->
        <test-method signature="singleValueIsReplied()[pri:0, instance:TestCalculate@6a2b953e]" started-at="2021-01-10T20:02:13 IST" name="singleValueIsReplied" finished-at="2021-01-10T20:02:13 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- singleValueIsReplied -->
        <test-method signature="threeNumbersCommaDelimitersBothWaysReturnSum()[pri:0, instance:TestCalculate@6a2b953e]" started-at="2021-01-10T20:02:13 IST" name="threeNumbersCommaDelimitersBothWaysReturnSum" finished-at="2021-01-10T20:02:13 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- threeNumbersCommaDelimitersBothWaysReturnSum -->
        <test-method signature="twoNumbersCommaDelimitersReturnSum()[pri:0, instance:TestCalculate@6a2b953e]" started-at="2021-01-10T20:02:13 IST" name="twoNumbersCommaDelimitersReturnSum" finished-at="2021-01-10T20:02:13 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- twoNumbersCommaDelimitersReturnSum -->
        <test-method signature="twoNumbersNewLineDelimitersReturnSum()[pri:0, instance:TestCalculate@6a2b953e]" started-at="2021-01-10T20:02:13 IST" name="twoNumbersNewLineDelimitersReturnSum" finished-at="2021-01-10T20:02:13 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- twoNumbersNewLineDelimitersReturnSum -->
      </class> <!-- TestCalculate -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
